### ISSUE TITLE
Scoped Implementation of AddBlazorServerAccessTokenManagement Causes Token Store Data Loss

### ISSUE THREAD

**Issue by BartoGabriel** [DuendeSoftware/foss#79]
**Description:**
In the previous version of the `AddBlazorServerAccessTokenManagement` method, the `IUserTokenStore` was registered as a singleton:

```csharp
/// <summary>
/// Adds implementations of services that enable access token management in
/// Blazor Server.
/// </summary>
/// <typeparam name="TTokenStore">An IUserTokenStore implementation. Blazor
/// Server requires an IUserTokenStore because the default token store
/// relies on cookies, which are not present when streaming updates over a
/// blazor circuit. </typeparam>
public static IServiceCollection AddBlazorServerAccessTokenManagement<TTokenStore>(this IServiceCollection services)
    where TTokenStore : class, IUserTokenStore
{
    services.AddSingleton<IUserTokenStore, TTokenStore>();
    services.AddScoped<IUserAccessor, BlazorServerUserAccessor>();
    services.AddCircuitServicesAccessor();
    services.AddHttpContextAccessor(); // For SSR

    return services;
}
```

However, in the current version, the `IUserTokenStore` is now registered as scoped:

```csharp
/// <summary>
/// Adds implementations of services that enable access token management in
/// Blazor Server.
/// </summary>
/// <typeparam name="TTokenStore">An IUserTokenStore implementation. Blazor
/// Server requires an IUserTokenStore because the default token store
/// relies on cookies, which are not present when streaming updates over a
/// blazor circuit. </typeparam>
public static IServiceCollection AddBlazorServerAccessTokenManagement<TTokenStore>(this IServiceCollection services)
    where TTokenStore : class, IUserTokenStore
{
    services.AddScoped<IUserTokenStore, TTokenStore>();
    services.AddScoped<IUserAccessor, BlazorServerUserAccessor>();
    services.AddCircuitServicesAccessor();
    services.AddHttpContextAccessor(); // For SSR

    return services;
}
```

This change causes a critical issue where the state maintained by the `IUserTokenStore` is lost on each request. Since the store is now instantiated per scope, it does not retain its data between requests, which impacts scenarios where persistent token management is required for Blazor Server applications.

**Impact:**
- Loss of token store state between requests.
- Disrupts functionality dependent on persistent access tokens, especially in scenarios requiring long-lived user sessions.

**Steps to Reproduce:**
1. Register the `AddBlazorServerAccessTokenManagement` method with a scoped `IUserTokenStore`.
2. Attempt to store and retrieve access token information across multiple requests.
3. Observe that the token information is lost after the request ends.

**Expected Behavior:**
The `IUserTokenStore` should persist its state across requests to maintain token data integrity.

**Proposed Solution:**
Revert the `IUserTokenStore` registration to a singleton:

```csharp
services.AddSingleton<IUserTokenStore, TTokenStore>();
```

**Comment by josephdecock** [comment]
This was an intentional change because some implementations of the store (notably the store implementation for blazor in our BFF framework) have a dependency on the `AuthenticationStateProvider`, which can't be resolved in a singleton context.

Typically a server side session is stored somewhere more durable than in memory - e.g., a database or redis. Then the IUserTokenStore is merely accessing data stored elsewhere and can be created and destroyed at will.

You point out that this is especially a problem "in scenarios requiring long-lived user sessions". Well, if you're storing the sessions in memory in a singleton, whenever your server is restarted, all the (long-lived) sessions are lost. Also, you're not going to be able to scale out.

That said, we did run into this in our sample app. Our sample app's user token store persists tokens in memory, and is not intended as production worthy (for the reasons I mention above). In that sample, it was easy to fix this by simply changing the collection that stores the sessions to be a static. Here's the pr: https://github.com/DuendeSoftware/foss/pull/77/files

**Comment by BartoGabriel** [comment]
Thanks for the explanation! I understand now why the `IUserTokenStore` needed to be scoped and not singleton. Your point about durable storage and scalability makes sense. I appreciate the clarification.
